name: Build and Push Docker Image

on:
  push:
    paths:
      - 'openaictl/**'
      - '.github/workflows/docker-build-and-push.yml'
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            gshiva/openaictl:latest
            gshiva/openaictl:${{ github.sha }}

      # Optionally add QEMU for cross-platform builds
      - name: Install QEMU for ARM builds
        uses: docker/setup-qemu-action@v2
